import type { Competition, RawCompetitionResponse } from "@oc/types";

export function mapComp(c: RawCompetitionResponse): Competition {
  return {
    id: c._id || c.id || "",
    _id: c._id,
    title: c.title ?? "",
    slug: c.slug ?? "",
    description: c.description,
    shortDescription: c.shortDescription,
    category: c.category,
    isCashOnly: c.isCashOnly,
    status: c.status ?? "draft",
    ticketPrice: c.ticketPrice ?? c.price ?? 0,
    price: c.price,
    originalPrice: c.originalPrice,
    imageUrl: c.imageUrl,
    prizeImageUrl: c.prizeImageUrl,
    heroImageUrl: c.heroImageUrl,
    prizeImages: c.prizeImages,
    drawDate: c.drawDate,
    endDate: c.endDate,
    startDate: c.startDate,
    prizeValue: c.prizeValue ?? 0,
    totalTickets: c.maxTickets ?? c.totalTickets ?? 0,
    maxTickets: c.maxTickets ?? 0,
    soldTickets: c.ticketsSold ?? c.soldTickets ?? 0,
    ticketsSold: c.ticketsSold ?? c.soldTickets ?? 0,
    ticketsHeld: c.ticketsHeld,
    availableTickets: c.availableTickets,
    percentageTaken: c.percentageTaken,
    maxTicketsPerUser: c.maxTicketsPerUser,
    isFeatured: c.isFeatured,
    displayOrder: c.displayOrder,
    requireSignIn: c.requireSignIn,
    question: c.question,
    questionOptions: c.questionOptions,
    currency: c.currency ?? "GBP",
    createdAt: c.createdAt ?? new Date().toISOString(),
    updatedAt: c.updatedAt ?? new Date().toISOString(),
  };
}
